import {
  NEXT_PUBLIC_SITE_NAME,
  NEXT_PUBLIC_SITE_URL,
} from '@/config/env';

export { REVALIDATE_POSTS, REVALIDATE_PAGES, REVALIDATE_CATEGORIES, REVALIDATE_MEDIA, REVALIDATE_MENUS, DEFAULT_PER_PAGE, CACHE_TAGS } from '@/config/env';

export {
  NEXT_PUBLIC_SITE_NAME as SITE_NAME,
  NEXT_PUBLIC_SITE_URL as FRONTEND_URL,
};
